In [2]:
# Creating Numpy arrays
import numpy as np

# Converting from a list
#Lets start with a list

my_list1 = [1,2,3,4]

my_array1 = np.array(my_list1)



In [4]:
#Print out array

my_array1

array([1, 2, 3, 4])

In [5]:
# Make another list
my_list2 = [11,22,33,44]

#Make a list of lists
my_lists = [my_list1,my_list2]

#Make multi-dimensional array
my_array2 = np.array(my_lists)

#Show array
my_array2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [6]:
#Lets get the size of the array
my_array2.shape

(2L, 4L)

In [7]:
#Find out the data tyoe of the array
my_array2.dtype

dtype('int32')

In [8]:
#Making special case arrays

#Zeros
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [11]:
#Ones
np.ones((5,5))

dtype('float64')

In [9]:
# An empty array -> Uninitialized values

np.empty(5)
# np.empty((3,4))


array([ 1.  ,  2.75,  6.  , 10.75, 17.  ])

In [16]:
#Identity array
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [4]:
# Using a range

np.arange(5)

array([0, 1, 2, 3, 4])