In [1]:
import numpy as np



In [2]:
#Create an array
arr = np.arange(5)

In [3]:
#Saving array on disk in binary format (file extension .npy)
np.save('my_array',arr)

In [4]:
#Change arr
arr = np.arange(10)
#Show
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
#Lets see the original saved copy
np.load('my_array.npy')

array([0, 1, 2, 3, 4])

In [6]:
#Saving multiple arrays into a zip file
np.savez('two_arrays.npz',x=arr,y=arr)

In [7]:
#Now loading multiple arrays
archive_array = np.load('two_arrays.npz')


#Show
archive_array['x']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
#Now lets remove them from the memory
# THIS IS NOT WORKING IMMEDIATELY
# rm my_array.npy
# rm my_test_text.txt
# rm 'two_arrays.npz'

# You need to install rm using pip3, the write !rm my_array.npy

In [ ]:
#Now saving and loading text files

arr = np.array([[1,2,3],[4,5,6]])
np.savetxt('my_test_text.txt',arr,delimiter=',')

In [ ]:
arr = np.loadtxt('my_test_text.txt',delimiter = ',')
arr


array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])